name: orhs2
channels:
  - conda-forge
  - mantid/label/nightly
  - neutrons
  - mantid-ornl
  - mantid-ornl/label/rc
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - adwaita-icon-theme=48.1=unix_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - alsa-lib=1.2.14=hb9d3cd8_0
  - anaconda-cli-base=0.5.2=pyhd8ed1ab_0
  - anaconda-client=1.13.0=pyh29332c3_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.9.0=pyh29332c3_0
  - aom=3.9.1=hac33072_0
  - archspec=0.2.5=pyhd8ed1ab_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311h9ecbd09_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - attr=2.5.1=h166bdaf_1
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhd8ed1ab_1
  - beautifulsoup4=4.13.4=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.6=he440d0b_1
  - boa=0.17.0=pyhd8ed1ab_3
  - boltons=25.0.0=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.1.0=py311hfdbb021_3
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.18.0=h3122c55_0
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - certifi=2025.6.15=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - cfgv=3.3.1=pyhd8ed1ab_1
  - chardet=5.2.0=pyhd8ed1ab_3
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - cmarkgfm=2024.11.20=py311h9ecbd09_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - conda=24.1.2=py311h38be061_0
  - conda-build=3.28.4=py311h38be061_0
  - conda-index=0.6.1=pyhd8ed1ab_0
  - conda-libmamba-solver=24.9.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.11.0=pyhd8ed1ab_1
  - conda-verify=3.4.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py311hd18a35c_0
  - coverage=7.9.1=py311h2dc5d0c_0
  - cpython=3.11.13=py311hd8ed1ab_0
  - cryptography=45.0.4=py311hafd3f86_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.14=py311hfdbb021_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distlib=0.3.9=pyhd8ed1ab_1
  - distro=1.9.0=pyhd8ed1ab_1
  - docutils=0.21.2=pyhd8ed1ab_1
  - double-conversion=3.3.1=h5888daf_0
  - elfutils=0.192=h7f4e02f_1
  - epoxy=1.5.10=h166bdaf_1
  - euphonic=1.4.4=py311h9f3472d_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - execnet=2.1.1=pyhd8ed1ab_1
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.0=h5888daf_0
  - ffmpeg=7.1.1=gpl_h127656b_906
  - filelock=3.18.0=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - fmt=11.1.4=h07f6e7f_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.4=py311h2dc5d0c_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freeglut=3.2.2=ha6d2627_3
  - freeimage=3.18.0=h3a85593_22
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - future=1.0.0=pyhd8ed1ab_2
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - gettext=0.24.1=h5888daf_0
  - gettext-tools=0.24.1=h5888daf_0
  - giflib=5.2.2=hd590300_0
  - glib=2.84.1=h07242d1_0
  - glib-tools=2.84.1=h4833e2c_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.8.9=h86084c0_1
  - graphite2=1.3.14=h5888daf_0
  - gsl=2.8=hbf7d49c_1
  - gst-plugins-base=1.24.11=h651a532_0
  - gstreamer=1.24.11=hc37bda9_0
  - gtk3=3.24.43=h0c6a113_5
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.14.0=nompi_py311h7f87ba5_100
  - harfbuzz=11.2.1=h3beb420_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h2d575fe_101
  - hicolor-icon-theme=0.17=ha770c72_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - id=1.5.0=pyh29332c3_0
  - identify=2.6.12=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - imagecodecs=2025.3.30=py311hbd51a34_1
  - imageio=2.37.0=pyhfb79c49_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - imath=3.1.12=h7955e40_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipympl=0.9.7=pyhd8ed1ab_1
  - ipython=9.3.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jaraco.classes=3.4.0=pyhd8ed1ab_2
  - jaraco.context=6.0.1=pyhd8ed1ab_0
  - jaraco.functools=4.1.0=pyhd8ed1ab_0
  - jasper=4.2.5=h1920b20_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jeepney=0.9.0=pyhd8ed1ab_0
  - jemalloc=5.2.0=he1b5a44_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - json5=0.12.0=pyhd8ed1ab_0
  - jsoncpp=1.9.6=hf42df4d_1
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py311h38be061_1
  - jsonschema=4.24.0=pyhd8ed1ab_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.24.0=hd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhe01879c_2
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - jxrlib=1.1=hd590300_3
  - keyring=25.6.0=pyha804496_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py311hd18a35c_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h1423503_5
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.22.5=h84d6215_0
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.7.7=h75ea233_4
  - libasprintf=0.24.1=h8e693c7_0
  - libasprintf-devel=0.24.1=h8e693c7_0
  - libass=0.17.3=h52826cd_2
  - libavif16=1.3.0=h766b0b6_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libboost=1.84.0=h6c02f8c_7
  - libboost-python=1.84.0=py311h5b7b71f_7
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=31_he106b2a_openblas
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang-cpp19.1=19.1.7=default_hb5137d0_3
  - libclang13=20.1.7=default_he06ed0a_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.24.1=h5888daf_0
  - libgettextpo-devel=0.24.1=h5888daf_0
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.1=h2ff4ddf_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_2
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libhwy=1.2.0=hf40a0c7_0
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.8=ha4ef2c3_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libjxl=0.11.1=h7b0646d_2
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblief=0.12.3=h27087fc_0
  - libllvm15=15.0.7=ha7bfdaf_5
  - libllvm19=19.1.7=ha7bfdaf_1
  - libllvm20=20.1.7=he9d0ab4_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libmamba=1.5.12=he771761_1
  - libmambapy=1.5.12=py311h5f9230d_1
  - libmicrohttpd=1.0.1=hbc5bc17_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenvino=2025.0.0=hdc3f47d_3
  - libopenvino-auto-batch-plugin=2025.0.0=h4d9b6c2_3
  - libopenvino-auto-plugin=2025.0.0=h4d9b6c2_3
  - libopenvino-hetero-plugin=2025.0.0=h981d57b_3
  - libopenvino-intel-cpu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-intel-gpu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-intel-npu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-ir-frontend=2025.0.0=h981d57b_3
  - libopenvino-onnx-frontend=2025.0.0=h0e684df_3
  - libopenvino-paddle-frontend=2025.0.0=h0e684df_3
  - libopenvino-pytorch-frontend=2025.0.0=h5888daf_3
  - libopenvino-tensorflow-frontend=2025.0.0=h684f15b_3
  - libopenvino-tensorflow-lite-frontend=2025.0.0=h5888daf_3
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.49=h943b412_0
  - libpq=16.9=h87c4ccc_0
  - libprotobuf=5.29.3=h501fc15_1
  - libraw=0.21.4=h9969a89_0
  - librdkafka=2.10.1=h2e2c4f7_0
  - librsvg=2.58.4=he92a37e_3
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsolv=0.7.33=h7955e40_0
  - libsqlite=3.50.1=hee588c1_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libsystemd0=257.6=h4e0b6ca_0
  - libtasn1=4.20.0=hb9d3cd8_0
  - libtiff=4.7.0=hf01ce69_5
  - libudev1=257.6=hbe16f8c_0
  - libunistring=0.9.10=h7f98852_0
  - libunwind=1.6.2=h9c3ff4c_0
  - liburing=2.9=h84d6215_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.14.1=hac33072_0
  - libwebp=1.5.0=hae8dbeb_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - lz4=4.4.4=py311h8c6ae76_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - mantid=6.12.20250618.1055=py311h281d3ad_0
  - mantiddocs=6.12.20250618.1055=h14a4261_0
  - mantidqt=6.12.20250618.1055=py311h77c3443_0
  - mantidworkbench=6.12.20250618.1055=py311h5995cf5_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py311h2dc5d0c_1
  - matplotlib=3.9.4=py311h38be061_0
  - matplotlib-base=3.9.4=py311h2b939e6_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdit-py-plugins=0.4.2=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - menuinst=2.2.0=py311h38be061_0
  - mistune=3.1.3=pyh29332c3_0
  - more-itertools=10.7.0=pyhd8ed1ab_0
  - mpg123=1.32.9=hc50e24c_0
  - msgpack-python=1.1.1=py311hd18a35c_0
  - mslice=2.11_83=pyh6af92e8_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.4=h27087fc_0
  - mysql-common=9.0.1=h266115a_6
  - mysql-libs=9.0.1=he0572af_6
  - myst-parser=4.0.1=pyhd8ed1ab_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.10.1=h4a9d5aa_0
  - networkx=3.5=pyhe01879c_0
  - nh3=0.2.21=py39h77e2912_1
  - nodeenv=1.9.1=pyhd8ed1ab_1
  - notebook=7.4.3=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - nspr=4.36=h5888daf_0
  - nss=3.112=h159eef7_0
  - numpy=2.1.3=py311h71ddf71_0
  - occt=7.9.0=novtk_h09ba48e_103
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openexr=3.3.4=h2cd1444_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.0=h7b32b05_1
  - orsopy=1.2.1=pyhd8ed1ab_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.0=py311h7db5c69_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.3=h9ac818e_1
  - parso=0.8.4=pyhd8ed1ab_1
  - patch=2.7.6=h7f98852_1002
  - patchelf=0.18.0=h3f2d84a_2
  - pcre2=10.44=hc749103_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.2.1=py311h1322bbf_0
  - pint=0.24.4=pyhd8ed1ab_1
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.2=h29eaf8c_0
  - pkginfo=1.12.1.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.8=pyhe01879c_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - poco=1.14.2=h0a6e815_0
  - pre-commit=4.2.0=pyha770c72_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - prompt_toolkit=3.0.51=hd8ed1ab_0
  - psutil=7.0.0=py311h9ecbd09_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=hac146a9_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-lief=0.12.3=py311ha362b79_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycifrw=4.4.6=py311h9ecbd09_2
  - pycosat=0.6.6=py311h9ecbd09_2
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py311hdae7d1d_0
  - pydantic-settings=2.9.1=pyh3cfb1c2_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyproject_hooks=1.2.0=pyhd8ed1ab_1
  - pyqt=5.15.9=py311hf0fb5b6_5
  - pyqt5-sip=12.12.2=py311hb755f60_5
  - pyqtwebengine=5.15.9=py311hd529140_5
  - pyside6=6.7.3=py311h9053184_1
  - pysocks=1.7.1=pyha55dd90_7
  - pystack=1.4.1=py311hc7f6798_1
  - pytest=8.4.1=pyhd8ed1ab_0
  - pytest-cov=6.2.1=pyhd8ed1ab_0
  - pytest-xdist=3.7.0=pyhd8ed1ab_0
  - python=3.11.13=h9e4cc4f_0_cpython
  - python-build=1.2.2.post1=pyhff2d567_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-dotenv=1.1.0=pyh29332c3_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-gil=3.11.13=hd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-libarchive-c=5.3=pyhe01879c_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=7_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.8.0=py311h9f3472d_0
  - pyyaml=6.0.2=py311h2dc5d0c_2
  - pyzmq=27.0.0=py311h7deb3e3_0
  - qhull=2020.2=h434a139_5
  - qscintilla2=2.13.4=py311ha10a086_0
  - qt-gtk-platformtheme=5.15.8=he21a4df_1
  - qt-main=5.15.8=h374914d_26
  - qt-webengine=5.15.8=h8f589be_8
  - qt6-main=6.7.3=h20baabe_0
  - qtawesome=1.4.0=pyh9208f05_1
  - qtconsole=5.6.1=pyhd8ed1ab_2
  - qtconsole-base=5.6.1=pyha770c72_2
  - qtpy=2.4.3=pyhd8ed1ab_1
  - quasielasticbayes=0.3.0=py311h7bc6544_0
  - quickbayes=1.0.2=pyhd8ed1ab_0
  - rapidjson=1.1.0.post20240409=h3f2d84a_2
  - rav1e=0.7.1=h8fae777_3
  - readchar=4.2.0=pyhd8ed1ab_1
  - readline=8.2=h8c095d6_2
  - readme_renderer=44.0=pyhd8ed1ab_1
  - referencing=0.36.2=pyh29332c3_0
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - requests=2.32.4=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986=2.0.0=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=14.0.0=pyh29332c3_0
  - ripgrep=14.1.1=h8fae777_1
  - roman-numerals-py=3.1.0=pyhd8ed1ab_0
  - rpds-py=0.25.1=py311hdae7d1d_0
  - ruamel.yaml=0.18.14=py311h9ecbd09_0
  - ruamel.yaml.clib=0.2.8=py311h9ecbd09_1
  - scikit-image=0.25.2=py311h7db5c69_1
  - scipy=1.15.2=py311h8f841c2_0
  - sdl2=2.32.54=h3f2d84a_0
  - sdl3=3.2.14=he3e324a_0
  - secretstorage=3.3.3=py311h38be061_3
  - seekpath=2.1.0=pyhd8ed1ab_1
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - sip=6.7.12=py311hb755f60_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - snapred=1.2.0rc3=py310
  - sniffio=1.3.1=pyhd8ed1ab_1
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - soupsieve=2.7=pyhd8ed1ab_0
  - spglib=2.6.0=py311h9e811c2_0
  - sphinx=8.2.3=pyhd8ed1ab_0
  - sphinx_rtd_theme=3.0.1=pyha770c72_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jquery=4.1=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.0.2=h5888daf_0
  - tbb=2022.1.0=h4ce085d_0
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2025.6.11=pyhd8ed1ab_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5.1=py311h9ecbd09_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.10.1=pyh29332c3_0
  - twine=6.1.0=pyh29332c3_0
  - typer=0.16.0=pyh167b9f4_0
  - typer-slim=0.16.0=pyhe01879c_0
  - typer-slim-standard=0.16.0=hf964461_0
  - types-python-dateutil=2.9.0.20250516=pyhd8ed1ab_0
  - typing-extensions=4.14.0=h32cad80_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - ukkonen=1.0.1=py311hd18a35c_5
  - unicodedata2=16.0.0=py311h9ecbd09_0
  - unixodbc=2.3.12=h661eb56_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - versioningit=3.2.0=pyhd8ed1ab_0
  - virtualenv=20.31.2=pyhd8ed1ab_0
  - watchgod=0.7=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_1
  - wayland-protocols=1.45=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h3f2d84a_0
  - zeromq=4.3.5=h3b0a872_7
  - zfp=1.0.1=h5888daf_2
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.4=h7955e40_0
  - zstandard=0.23.0=py311h9ecbd09_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - bm3d==4.0.3
    - bm3d-streak-removal==0.2.0
    - bm4d==4.2.5
    - greenlet==3.2.3
    - playwright==1.52.0
    - pyee==13.0.0
    - pytest-base-url==2.1.0
    - pytest-playwright==0.7.0
    - python-slugify==8.0.4
    - text-unidecode==1.3

prefix: "/SNS/users/66j/micromamba/envs/snapwrapWithJupyter"
